name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn install

      - name: Log Node & TypeScript versions
        run: |
          node -v
          npx tsc -v

      - name: Check Formatting
        run: yarn formatting:check

      - name: Check Linting
        run: yarn lint:check

      - name: Check Types
        run: yarn check:types

      - name: Build styles
        run: yarn preview:style:variables

      - name: Bundle package (build NPM package)
        run: yarn bundle

      - name: Run DocGen scaffold (DEV)
        run: yarn test:scaffold

      - name: Run DocGen (DEV)
        run: yarn test:run

      - name: Run DocGen (PROD)
        run: yarn test:prod:run

      - name: Test Publish (Dry-Run)
        run: yarn test:publish
