name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Enable corepack and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.28.0 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Log Node & TypeScript versions
        run: |
          node -v
          pnpm tsc -v

      - name: Check Formatting
        run: pnpm formatting:check

      - name: Check Linting
        run: pnpm lint:check

      - name: Check Types
        run: pnpm check:types

      - name: Build styles
        run: pnpm preview:style:variables

      - name: Bundle package (build NPM package)
        run: pnpm bundle

      - name: Run DocGen scaffold (DEV)
        run: pnpm test:scaffold

      - name: Run DocGen (DEV)
        run: pnpm test:run

      - name: Run DocGen (PROD)
        run: pnpm test:prod:run

      - name: Test Publish (Dry-Run)
        run: pnpm test:publish
